service: youtube-api
frameworkVersion: '3'

provider:
     name: aws
     runtime: nodejs18.x
     region: sp-douth-1

  functions:
    youtubeHelloFn:
        handler: hello.handler
        events:
           - httpsApi:
                path: /hello
                method: GET
